
server:
    error:
        include-message: always
spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${DATABASE_PASSWORD}
        platform: postgres
        url: jdbc:${DATABASE_URL}
        username: ${DATABASE_USER}
    jackson:
        deserialization:
            use_java_array_for_json_array: true
        serialization:
            write-dates-as-timestamps: false
    jpa:
        database: POSTGRESQL
        generate-ddl: true
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                    create_namespaces: true
                show_sql: false
                format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    web:
        resources:
            static-locations: classpath:/static/browser