security:
    basic:
        enabled: false

server:
    error:
        include-message: always
spring:
    config:
        import: optional:file:.env[.properties]
    datasource:
        driver-class-name: org.h2.Driver
        password: password
        url: jdbc:h2:mem:testdb
        username: sa
    jackson:
        deserialization:
            use_java_array_for_json_array: true
        serialization:
            write-dates-as-timestamps: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: POSTGRESQL
        generate-ddl: true
        properties:
            hibernate:
                hbm2ddl:
                    auto: create-drop
                    create_namespaces: true
                show_sql: false
                connection:
                    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS core
        show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
